### PR TITLE
fix: resolve OpenAPI validators at the correct stability level

### LINKED ISSUE #250: versionSlice Resolve does not resolve to an appropriate version.
Adding the below test case to `TestVersionSlice`:
```
{
    versions: VersionSlice{
        MustParseVersion("2021-09-06~beta"),
	MustParseVersion("2021-09-07"),
	MustParseVersion("2021-09-08~beta"),
	MustParseVersion("2021-09-09~experimental"),
    },
    first: "2021-09-06~beta",
    last:  "2021-09-09~experimental",
    matchTests: []matchTest{{
        match:  "2021-09-10",
	result: "2021-09-07",
    }},
}
```
yields to a `no matching version` error.

### PR DESCRIPTION
**Pull request by cmars**
Related to snyk/vervet#248, a similar stability version issue affects
validation middleware "versionware".

This breaking change replaces VersionSlice.Resolve with
VersionIndex.Resolve.

It turns out resolving versions correctly across date and stability
requires tracking the most recent release per stability for each
distinct version date. This requires a different structure for indexing;
a simple []Version slice does not suffice for an O(logN) search
complexity.

Fixes #250.

### CODE REVIEW

File: versionware/validator_resolve_test.go [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+	}, {
+		url:    "/foo?color=red&version=2022-07-20~beta",
+		status: 200,
+	}, {
+		url:    "/foo?flavor=flav&version=2022-07-21",
+		status: 200,
+	}, {
+		url:    "/foo?version=2022-01-01",
+		status: 404,
+	}}
```
Comment (jcsackett) [inline versionware/validator_resolve_test.go:91]: It'll be a lot easier to sort out what might be going wrong here if we had test names for the cases; e.g. "no resolved version", "resolved exact match" etc.

Not necessary, but a suggestion.

**Review by jcsackett — APPROVED** [review]

**Comment by cmars** [comment]
@jlourenc found a problem with `VersionSlice.Resolve`. Looking into it, we found that resolving the correct stability version requires a different data structure. Rather than add it alongside a broken search implementation, I decided to fix it in a new major rev.

File: version.go [hunk 2]
```diff
@@ -227,75 +241,108 @@ func VersionDateStrings(vs []Version) []string {
...
-		return Version{}, err
+// VersionIndex provides a search over versions, resolving which version is in
+// effect for a given date and stability level.
+type VersionIndex struct {
+	versions []effectiveVersion
+}
+
+type effectiveVersion struct {
+	date        time.Time
+	stabilities map[Stability]time.Time
```
Comment (jlourenc) [inline version.go:255]: nit: Using the `map` here is totally fine. Just bare in mind that `Stability` is defined as integer. More than that the integers are consecutive. So it could be defined as an array (not a slice) which gives you fast lookup, allows you to iterate through elements in (reverse) order.

File: version.go [hunk 3]
```diff
@@ -227,75 +241,108 @@ func VersionDateStrings(vs []Version) []string {
...
+func NewVersionIndex(vs VersionSlice) *VersionIndex {
+	sort.Sort(vs)
+	var evs []effectiveVersion
+	evIndex := -1
+	currentStabilities := map[Stability]time.Time{}
+	for i := range vs {
+		if evIndex == -1 || !evs[evIndex].date.Equal(vs[i].Date) {
+			evs = append(evs, effectiveVersion{
+				date:        vs[i].Date,
+				stabilities: map[Stability]time.Time{},
```
Comment (jlourenc) [inline version.go:269]: You could do `stabilities: maps.Clone(currentStabilities)` if you're willing to upgrade the minimum Go version supported by vervet to `1.17` which is now unsupported by the Go team since the release of Go 1.19.

https://pkg.go.dev/golang.org/x/exp@v0.0.0-20220927162542-c76eaa363f9d/maps#Clone

File: version.go [hunk 4]
```diff
@@ -227,75 +241,108 @@ func VersionDateStrings(vs []Version) []string {
...
-// ResolveIndex returns the slice index of the most recent Version in the slice
-// with equal or greater stability.
-//
-// This method requires that the VersionSlice has already been sorted with
-// sort.Sort, otherwise behavior is undefined.
-func (vs VersionSlice) ResolveIndex(q Version) (int, error) {
-	lower, curr, upper := 0, len(vs)/2, len(vs)
+// resolveIndex performs a binary search on the stability versions in effect on
+// the query date.
+func (vi *VersionIndex) resolveIndex(query time.Time) (int, error) {
```
Comment (jlourenc) [inline version.go:286]: I think this function can be simplified to:
```
func (vi VersionIndex) resolveIndex(query time.Time) (int, error) {
        if len(vi.versions) == 0 || vi.versions[0].date.After(query) {
                // empty slice or oldest version more recent than query
		return -1, ErrNoMatchingVersion
	}

	lower, curr, upper := 0, len(vi.versions)/2, len(vi.versions)
	for lower < upper-1 {
		if vi.versions[curr].date.After(query) {
			upper = curr
		} else {
			lower = curr
		}
		curr = lower + (upper-lower)/2
	}

	return lower, nil
}
```

File: version.go [hunk 5]
```diff
@@ -227,75 +241,108 @@ func VersionDateStrings(vs []Version) []string {
...
+	i, err := vi.resolveIndex(query.Date)
+	if err != nil {
+		return Version{}, err
+	}
+	for stab, ok := query.Stability, true; ok; stab, ok = stab.Next() {
+		matchDate, ok := vi.versions[i].stabilities[stab]
+		if ok {
+			return Version{Date: matchDate, Stability: stab}, nil
+		}
+	}
```
Comment (jlourenc) [inline version.go:324]: I think this introduces a slightly different behaviour than before. It returns the "lowest" stability available that is equal or greater of the query's stability. Previously, it would have returned the greatest stability available.

File: version_test.go [hunk 6]
```diff
@@ -143,13 +142,19 @@ func TestVersionSlice(t *testing.T) {
...
+		}, {
+			match:  "2021-06-11~beta",
+			result: "2021-06-10~beta",
+		}, {
+			match:  "2021-06-11",
 			result: "2021-06-10",
 		}, {
 			match:  "2021-06-10~experimental",
-			result: "2021-06-10",
+			result: "2021-06-10~beta",
```
Comment (jlourenc) [inline version_test.go:154]: I guess this is the change of behaviour I've mentioned just above. It's great to see our tests have captured that 🎉

File: spec.go [hunk 7]
```diff
@@ -76,21 +77,15 @@ func (sv *SpecVersions) Versions() VersionSlice {
...
-	// matching the requested stability. ResolveIndex may overshoot it because
-	// it returns equal or greater stability.
-	for ; i >= 0; i-- {
-		checkVersion := sv.versions[i]
-		if dateCmp, stabilityCmp := checkVersion.compareDateStability(&v); dateCmp <= 0 && stabilityCmp == 0 {
-			return sv.documents[i], nil
-		}
+	doc, ok := sv.documents[resolvedVersion]
+	if !ok {
+		return nil, ErrNoMatchingVersion
```
[the remark this answers is not in the document]
Comment (cmars) [reply spec.go:86]: Agree, such a case would be caused by a regression in either `newSpecVersions` or `NewVersionIndex`. A panic seems more appropriate here.

File: version.go (hunk 4 above)
Comment (cmars) [reply version.go:283]: Much nicer, thanks!

File: version.go (hunk 2 above)
Comment (cmars) [reply version.go]: Stability levels have become well-enough defined by this point that I'm ready to fully embrace their inner int nature. Thanks for the nudge here :)

File: version.go (hunk 3 above)
Comment (cmars) [reply version.go]: Going with the slice approach.

File: version.go (hunk 5 above)
Comment (cmars) [reply version.go]: Good callout here. It turns out there are two different kinds of "resolving" needed, which answer two different questions:

* I want to interact with a _service's API_ at a given stability on a given date. The versions have already been compiled from resources such that a version date+stability exists in my index for each available distinct API release. What is the best match?
* I want to comple a service-level API spec from many resources. When looking at each resource, what is the most stable API available from that _resource_ on a given date, greater than or equal to a minimum stability? In this scenario, a resource may have only one release per day (due to the directory structure used for expressing resource versions).

The first case is the one most will care about -- this is what you would typically use to decide what version of a service you want to interact with, what version of the service's OpenAPI spec should be used to validate a request for an arbitrary version, for example.

The second case is used only when compiling a service's OpenAPI specs.

File: version_test.go (hunk 6 above)
Comment (cmars) [reply version_test.go]: Indeed. I've expanded this test to provide coverage for both `Resolve` and `resolveForBuild`. There wasn't a clear enough distinction between the two prior to this PR, which was really at the root of the incorrect resolving behavior.

**Review by jcsackett — APPROVED** [review]
New changes look good, thanks!
